"use client";
import { useEffect, useState } from "react";
export default function Page(){
 const[blogs,setBlogs]=useState([]),[blogId,setBlogId]=useState(""),[posts,setPosts]=useState([]),[title,setTitle]=useState(""),[content,setContent]=useState(""),[status,setStatus]=useState("");
 async function loadBlogs(){const r=await fetch("/api/blogs",{cache:"no-store"}),d=await r.json();if(d.ok){setBlogs(d.blogs||[]);if(!blogId&&d.blogs?.[0]?.id)setBlogId(d.blogs[0].id)}}
 async function loadPosts(id){if(!id)return;const r=await fetch("/api/posts?blogId="+encodeURIComponent(id),{cache:"no-store"}),d=await r.json();setPosts(d.items||[])}
 useEffect(()=>{loadBlogs()},[]);useEffect(()=>{if(blogId)loadPosts(blogId)},[blogId]);
 async function createPost(publish){if(!blogId||!title.trim()||!content.trim()){setStatus("⚠️ عمر العنوان والمحتوى أولاً");return}setStatus(publish?"⏳ كننشر...":"⏳ كنحفظ...");const r=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({blogId,title,content})}),d=await r.json();if(!r.ok){setStatus("❌ "+(d.error?.message||d.error||"وقع خطأ"));return}if(publish&&d.id){const p=await fetch("/api/posts/"+d.id+"/publish?blogId="+encodeURIComponent(blogId),{method:"POST"});if(!p.ok){setStatus("❌ المنشور تخلق ولكن النشر فشل");return}setStatus("🚀 تنشر بنجاح!")}else setStatus("💾 تسجل كمسودة");setTitle("");setContent("");loadPosts(blogId)}
 return <main><div className="card"><h1>🤖 Blogger Auto Manager Robot</h1><p className="muted">لوحة تحكم بسيطة لإدارة مدونة Blogger ديالك.</p><div className="blog"><b>✅ Blogger مربوط بنجاح</b></div></div><div className="card"><h2>📝 منشور جديد</h2><label>المدونة</label><select value={blogId} onChange={e=>setBlogId(e.target.value)}>{blogs.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان المقال..."/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="كتب المقال هنا..." rows={14}/><div className="actions"><button onClick={()=>createPost(false)}>💾 حفظ كمسودة</button><button onClick={()=>createPost(true)}>🚀 نشر المقال</button></div>{status&&<p>{status}</p>}</div><div className="card"><h2>📚 آخر المنشورات</h2>{posts.length?posts.map(p=><div className="blog" key={p.id}><b>{p.title||"بدون عنوان"}</b><div className="muted">{p.published?"🟢 منشور":"🟡 مسودة"}</div></div>):<p className="muted">مازال ما كاين حتى منشور ظاهر هنا.</p>}</div></main>
}