"use client";
import{useEffect,useState}from"react";

function makeLabels(topic){return [...new Set(topic.trim().split(/\s+/).map(x=>x.replace(/[^\u0600-\u06FFa-zA-Z0-9-]/g,"")).filter(x=>x.length>2).slice(0,6))]}
function makeOriginalCover(topic){const safe=topic.replace(/[<>&"]/g,"").slice(0,70);const svg='<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="800" viewBox="0 0 1400 800"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#172554"/><stop offset="1" stop-color="#2563eb"/></linearGradient></defs><rect width="1400" height="800" rx="40" fill="url(#g)"/><circle cx="1180" cy="120" r="180" fill="white" opacity=".08"/><circle cx="180" cy="690" r="250" fill="white" opacity=".06"/><text x="700" y="365" text-anchor="middle" fill="white" font-family="Arial,sans-serif" font-size="62" font-weight="700">'+safe+'</text><text x="700" y="445" text-anchor="middle" fill="white" opacity=".78" font-family="Arial,sans-serif" font-size="28">Tiizkwiz • دليل عملي</text></svg>';return"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(svg)}
function buildFallbackArticle(topic){const t=topic.trim(),cover=makeOriginalCover(t);return{title:t+" — دليل عملي واضح",labels:makeLabels(t),content:'<article dir="rtl"><img src="'+cover+'" alt="'+t+'" style="width:100%;height:auto;border-radius:18px;margin-bottom:24px"/><p><strong>مقدمة:</strong> هذا الدليل كيركز على '+t+' بطريقة عملية وبعيدة عن الحشو، باش تكون عندك صورة واضحة قبل ما تبدا.</p><h2>شنو خاصك تعرف أولاً؟</h2><p>'+t+' ماشي موضوع كيتفهم بجملة وحدة. الأفضل هو تقسيمه لأجزاء صغيرة، فهم كل جزء، ومن بعد التطبيق ومراجعة النتيجة.</p><h2>كيفاش تبدا بطريقة منظمة؟</h2><ol><li>حدد الهدف ديالك بدقة.</li><li>جمع المعلومات الأساسية من مصادر موثوقة.</li><li>طبق خطوة صغيرة قبل الانتقال للمرحلة التالية.</li><li>راجع النتيجة وصحح الأخطاء.</li></ol><h2>أخطاء خاصك تتجنب</h2><ul><li>الاستعجال قبل فهم الأساسيات.</li><li>الاعتماد على معلومة واحدة بلا تحقق.</li><li>تكرار نفس الطريقة حتى إلا ما عطتش نتيجة.</li></ul><h2>الخلاصة</h2><p>الخلاصة هي أن التعامل مع '+t+' كيحتاج وضوح، تجربة، ومراجعة. بدا بخطوة بسيطة وخلي النتائج هي اللي توجه الخطوة اللي من بعدها.</p></article>'}}

export default function Page(){
 const[blogs,setBlogs]=useState([]),[blogId,setBlogId]=useState(""),[posts,setPosts]=useState([]),[title,setTitle]=useState(""),[content,setContent]=useState(""),[topic,setTopic]=useState(""),[labels,setLabels]=useState(""),[status,setStatus]=useState("");
 async function loadBlogs(){await fetch("/api/auth/persist",{method:"POST"}).catch(()=>{});const r=await fetch("/api/blogs",{cache:"no-store"}),d=await r.json();if(d.ok){setBlogs(d.blogs||[]);if(!blogId&&d.blogs?.[0]?.id)setBlogId(d.blogs[0].id)}}
 async function loadPosts(id){if(!id)return;const r=await fetch("/api/posts?blogId="+encodeURIComponent(id),{cache:"no-store"}),d=await r.json();setPosts(d.items||[])}
 useEffect(()=>{loadBlogs()},[]);
 useEffect(()=>{if(blogId)loadPosts(blogId)},[blogId]);
 async function generate(){
  if(!topic.trim()){setStatus("⚠️ كتب موضوع المقال أولاً");return}
  setStatus("⏳ كنوجد مقال أصلي...");
  try{
   const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic})});
   const d=await r.json();
   if(!r.ok){const a=buildFallbackArticle(topic);setTitle(a.title);setContent(a.content);setLabels(a.labels.join(", "));setStatus("⚠️ "+(d.error||"المولد الأصلي غير مربوط؛ جهزت نسخة آمنة للتعديل."));return}
   const a=d.article,cover=makeOriginalCover(topic);
   setTitle(a.title);setContent('<article dir="rtl"><img src="'+cover+'" alt="'+topic.replace(/"/g,"")+'" style="width:100%;height:auto;border-radius:18px;margin-bottom:24px"/>'+a.content_html+'<hr/><p style="font-size:13px;color:#64748b">محتوى أصلي أُعد خصيصاً لـTiizkwiz.</p></article>');setLabels(a.labels.join(", "));setStatus("✅ المقال الأصلي تجهز وفحصه الأساسي داز");
  }catch{const a=buildFallbackArticle(topic);setTitle(a.title);setContent(a.content);setLabels(a.labels.join(", "));setStatus("⚠️ تعذر الاتصال بالمولد؛ جهزت نسخة آمنة للتعديل.")}
 }
 async function createPost(publish){
  if(!blogId||!title.trim()||!content.trim()){setStatus("⚠️ خاص العنوان والمحتوى");return}
  setStatus(publish?"⏳ كننشر...":"⏳ كنحفظ كمسودة...");
  if(publish){const qr=await fetch("/api/quality-check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,title,content})}),qd=await qr.json();if(!qr.ok||!qd.publishable){setStatus("🛡️ توقف النشر: فحص الجودة أعطى "+(qd.score??0)+"/100. "+(qd.issues||["خاص المقال يتراجع قبل النشر."]).join(" • "));return}}
  const r=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({blogId,title,content,draft:!publish,labels:labels.split(",").map(x=>x.trim()).filter(Boolean)})}),d=await r.json();
  if(!r.ok){setStatus("❌ "+(d.error?.message||d.error||"وقع خطأ"));return}
  setStatus(publish?"🚀 تنشر بنجاح!":"💾 تسجل كمسودة");setTitle("");setContent("");loadPosts(blogId)
 }
 return <main><div className="card"><h1>🤖 Blogger Auto Manager Robot</h1><p className="muted">توليد مقال وتجهيزه بتصميم جذاب ثم إرساله مباشرة لـ Blogger.</p><div className="blog"><b>✅ Blogger مربوط بنجاح</b></div></div><div className="card"><h2>✨ توليد مقال كامل وجذاب</h2><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="مثلاً: أفضل طرق تنظيم الوقت"/><button onClick={generate}>✨ ولد المقال الجذاب</button></div><div className="card"><h2>📝 المنشور</h2><label>المدونة</label><select value={blogId} onChange={e=>setBlogId(e.target.value)}>{blogs.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان المقال..."/><input value={labels} onChange={e=>setLabels(e.target.value)} placeholder="الوسوم: مثال، تقنية، شرح"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="المحتوى..." rows={14}/><div className="actions"><button onClick={()=>createPost(false)}>💾 حفظ كمسودة</button><button onClick={()=>createPost(true)}>🚀 نشر المقال</button></div>{status&&<p>{status}</p>}</div><div className="card"><h2>🎨 تصميم Blogger</h2><p className="muted">Theme Tiizkwiz V4.1 جاهز للاستيراد في Blogger. من هنا تقدر تحمّلو، ومن بعد Blogger → Theme → Restore → Upload.</p><a href="https://raw.githubusercontent.com/hakimdino787-sketch/blogger-auto-manager-robot/main/themes/tiizkwiz-v4.1.xml" download target="_blank" rel="noreferrer"><button>⬇️ تحميل Theme XML</button></a> {blogId?<a href={"https://www.blogger.com/blog/themes/"+encodeURIComponent(blogId)} target="_blank" rel="noreferrer"><button>🎨 فتح Theme ديال المدونة</button></a>:<p className="muted">اختار المدونة أولاً.</p>}</div><div className="card"><h2>📚 آخر المنشورات</h2>{posts.length?posts.map(p=><div className="blog" key={p.id}><b>{p.title||"بدون عنوان"}</b><div className="muted">{p.published?"🟢 منشور":"🟡 مسودة"}</div></div>):<p className="muted">مازال ما كاين حتى منشور ظاهر هنا.</p>}</div></main>
}