import{NextResponse}from"next/server";
import{refreshSession}from"../../../../lib/session";
import{loadPersistentSession,savePersistentSession}from"../../../../lib/persistent-session";
const IMAGE_MAP=[
{match:"تنظيم الملفات والصور",url:"https://gen.krea.ai/images/92fc3ca8-2238-4e48-b228-a4cead15c48d.png"},
{match:"البحث على الإنترنت",url:"https://gen.krea.ai/images/74d0de0e-468e-4bb3-901e-3802519a1a59.png"},
{match:"تنظم وقتك",url:"https://gen.krea.ai/images/28c0027f-3108-428f-939d-56b9f9dad970.png"},
{match:"تحمي حساباتك",url:"https://gen.krea.ai/images/3973d470-43d8-4fe6-87ab-c4f3f0cc2a4a.png"},
{match:"تنظف الهاتف",url:"https://gen.krea.ai/images/ebe36f8d-7f44-430b-a82f-1b4d69f7ffe0.png"}
];
const DEFAULT_IMAGE="https://gen.krea.ai/images/66052f54-8e38-4f82-bb16-4664ed5d4128.png";
function imageFor(title){const hit=IMAGE_MAP.find(x=>String(title).includes(x.match));return hit?.url||DEFAULT_IMAGE}
function authorizedForEnhancement(req){const secret=process.env.CRON_SECRET;if(!secret)return false;return req.headers.get("authorization")===`Bearer ${secret}`}
function hasRealImage(body){return /<img\b[^>]*\bsrc\s*=\s*["']https?:\/\//i.test(body||"")}
function removeOldFakeImage(body){return String(body||"").replace(/<img\b[^>]*\bsrc\s*=\s*["']data:image\/svg\+xml[^"']*["'][^>]*\/?>/gi,"")}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function postWithRetry(url,opts){for(let i=0;i<5;i++){const pr=await fetch(url,opts);if(pr.ok)return pr;if(pr.status!==429&&pr.status!==403)return pr;await sleep(Math.min(32000,2000*(2**i)+Math.floor(Math.random()*1000)))}return fetch(url,opts)}
async function getSession(){let s=await loadPersistentSession();if(!s?.refresh_token)return{error:"خاص ربط Blogger مرة واحدة من الواجهة باش نحفظ جلسة التشغيل"};const rr=await refreshSession(s);if(rr.ok){s=rr.session;await savePersistentSession(s)}const blog=s.blogs?.[0];if(!blog?.id)return{error:"ما لقيتش مدونة Blogger مربوطة"};return{s,blog}}
export async function GET(req){const params=new URL(req.url).searchParams;if(params.get("mode")==="enhance"||params.get("enhance")==="1"){if(!authorizedForEnhancement(req))return NextResponse.json({ok:false,error:"يتطلب تعديل المسودات تصريح مهمة موثوقاً."},{status:401});return enhance(req);}const x=await getSession();if(x.error)return NextResponse.json({ok:false,error:x.error},{status:503});const{s,blog}=x;const list=await fetch("https://www.googleapis.com/blogger/v3/blogs/"+encodeURIComponent(blog.id)+"/posts?status=draft&maxResults=100&fetchBodies=false",{headers:{Authorization:"Bearer "+s.access_token}});if(!list.ok)return NextResponse.json({ok:false,error:"تعذر جلب المسودات: "+await list.text()},{status:list.status});const data=await list.json();return NextResponse.json({ok:true,blog:blog.name||blog.id,draftCount:(data.items||[]).length,drafts:(data.items||[]).map(p=>({id:p.id,title:p.title,updated:p.updated}))})}
async function enhance(req){if(process.env.BLOGGER_WRITES_ENABLED!=="true")return NextResponse.json({ok:false,error:"تعديل المسودات متوقف مؤقتاً بإعداد الحماية (BLOGGER_WRITES_ENABLED)."}, {status:423});const x=await getSession();if(x.error)return NextResponse.json({ok:false,error:x.error},{status:503});const{s,blog}=x;const list=await fetch("https://www.googleapis.com/blogger/v3/blogs/"+encodeURIComponent(blog.id)+"/posts?status=draft&maxResults=100&fetchBodies=true",{headers:{Authorization:"Bearer "+s.access_token}});if(!list.ok)return NextResponse.json({ok:false,error:"تعذر جلب مسودات Blogger: "+await list.text()},{status:list.status});const data=await list.json();const drafts=(data.items||[]).slice(0,3);const updated=[],failed=[];for(const p of drafts){const title=(p.title||"Tiizkwiz").trim();const body=p.content||"";const qr=await fetch(new URL("/api/quality-check",req.url),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:title,title,content:body})});const qd=await qr.json().catch(()=>({}));if(hasRealImage(body)){updated.push({id:p.id,title,score:qd.score??null,qualityOk:!!qd.ok,changed:false,imageAdded:false});continue}const img=imageFor(title);const alt=title.replace(/["<>]/g,"").slice(0,180);const cleaned=removeOldFakeImage(body);const newBody='<article dir="rtl"><img src="'+img+'" alt="'+alt+'" loading="eager" style="display:block;width:100%;max-width:1400px;height:auto;aspect-ratio:16/9;object-fit:cover;border-radius:18px;margin:0 0 24px" />'+cleaned+'</article>';const put=await postWithRetry("https://www.googleapis.com/blogger/v3/blogs/"+encodeURIComponent(blog.id)+"/posts/"+encodeURIComponent(p.id),{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+s.access_token},body:JSON.stringify({id:p.id,blog:{id:blog.id},title,content:newBody,labels:p.labels||[]})});if(put.ok)updated.push({id:p.id,title,score:qd.score??null,qualityOk:!!qd.ok,changed:true,imageAdded:true,imageUrl:img});else failed.push({id:p.id,title,error:await put.text()})}return NextResponse.json({ok:failed.length===0,mode:"enhance-existing-drafts-with-real-images",blog:blog.name||blog.id,found:drafts.length,updated,failed,published:0,generatedAt:new Date().toISOString()},{status:failed.length?502:200})}
export async function POST(req){if(!authorizedForEnhancement(req))return NextResponse.json({ok:false,error:"يتطلب تعديل المسودات تصريح مهمة موثوقاً."},{status:401});return enhance(req)}
